import Login from './pageobjects/cypress'
/// <reference types="cypress" />
const { describe } = require("mocha")
const obj = new Login();

describe('Redmine test cases',  function()  {
  //Positive testing
  it('Register on website',  function()  {
    obj.GoToPage()
    obj.Register()
  })
  it('Sign in on website',  function()  {
    obj.GoToPage()
    obj.LogIn()
  })
  it('Password recover',  function()  {
    obj.GoToPage()
    obj.PassRecover()
  })
  xit('Download redmine repository',  function()  {
    obj.GoToPage()
    obj.repoVersion()
    .click()
    obj.downloadRepo()
    .click()
  })
  it('Check available projects overview',  function()  {
    obj.GoToPage()
    obj.projectsButton()
    .click()
    obj.redmineProject()
    .click()
  })
  it('Check recently added defects',  function()  {
    obj.GoToPage()
    obj.activityButton()
    .click()
    obj.defect()
    .click()
  })
  it('Check Redmine versions implementation',  function()  {
    obj.GoToPage()
    obj.roadmapButton()
    .click()
    obj.roadmapImplementationVersion()
    .click()
  })
  it('Check Issues page filtration',  function()  {
    obj.GoToPage()
    obj.issuesButton()
    .click()
    obj.issuesAddFilter()
    .select("tracker_id")
    obj.issuesAddTrackerFilter()
    .select("2")
    obj.issuesApplyButton()
    .click()
  })
  it('Add new issue',  function()  {
    obj.GoToPage()
    obj.LogIn()
    obj.newIssueButton()
    .click()
    obj.makeNewIssue()
  })
  it('Check news page',  function()  {
    obj.GoToPage()
    obj.newsButton()
    .click()
    obj.news()
    .click()
  })
  it('Check forums page',  function()  {
    obj.GoToPage()
    obj.forumButton()
    .click()
    obj.helpTopic()
    .click()
  })
  it('Check repository page',  function()  {
    obj.GoToPage()
    obj.repoButton()
    .click()
    obj.repoPageCheck()
  })
  it('Change Redmine guide language',  function()  {
    obj.GoToPage()
    obj.helpButton()
    .click()
    obj.navigateToTranslation()
    .click()
    obj.translateToFrench()
    .click()
  })
  it('Check search filtation',  function()  {
    obj.GoToPage()
    obj.searchInput()
    obj.searchMessagesFilter()
    .click()
  })
  it('Buy redmine book',  function()  {
    obj.GoToPage()
    cy.scrollTo('bottom')
    obj.bookImage()
  })
  it('Check defect details through roadmap',  function()  {
    obj.GoToPage()
    obj.roadmapButton()
    .click()
    obj.roadmapImplementationVersion()
    .click()
    obj.defect()
    .click()
  })
  it('Increase number of defects shown',  function()  {
    obj.GoToPage()
    obj.issuesButton()
    .click()
    obj.issuesShow50Issues()
    .click()
  })
  it('Check project administarator profile',  function()  {
    obj.GoToPage()
    obj.projectsButton()
    .click()
    obj.redmineProject()
    .click()
    obj.redmimeProjectAdministrator()
    .click()
  })
  it('Сheck redmine plugin details',  function()  {
    obj.GoToPage()
    obj.resourcesPluginsButton()
    .click()
    obj.plugin()
    .click()
  })
  it('Check Changelog details by version',  function()  {
    obj.GoToPage()
    obj.resourcesChangelogButton()
    .click()
    obj.changelog5series()
    .click()
  })

  it('Сheck security vulnerability details',  function()  {
    obj.GoToPage()
    obj.resourcesSecurityButton()
    .click()
    obj.securityVulnerabilityDetail()
  })

  //Negative testing
  it('Register without data',  function()  {
    obj.GoToPage()
    obj.registerButton()
    .click()
    obj.submitRegisterButton()
    .click()
    obj.errorCheck()
  })
  it('Register with incorrect email',  function()  {
    obj.GoToPage()
    obj.registerButton()
    .click()
    obj.registerEnterEmail()
    obj.submitRegisterButton()
    .click()
    obj.errorCheck()
  })
})

