import Objects from './pageobjects/objects.page'
import Buttons from './pageobjects/buttons.page'
import Functions from './pageobjects/functions.page'

/// <reference types="cypress" />
const { describe } = require("mocha")

const obj = new Objects();
const btn = new Buttons();
const func = new Functions()


describe('Redmine test cases',  function()  {
  //Positive testing
  xit('Register on website',  function()  {
    func.GoToPage()
    func.Register()
  })
  xit('Sign in on website',  function()  {
    func.GoToPage()
    func.LogIn()
  })
  xit('Password recover',  function()  {
    func.GoToPage()
    func.PassRecover()
  })
  xit('Download redmine repository',  function()  {
    func.GoToPage()
    btn.repoVersionButton()
    .click()
    obj.downloadRepo()
    .click()
  })
  xit('Check available projects overview',  function()  {
    func.GoToPage()
    btn.projectsButton()
    .click()
    btn.redmineProjectButton()
    .click()
  })
  xit('Check recently added defects',  function()  {
    func.GoToPage()
    btn.activityButton()
    .click()
    obj.defect()
    .click()
  })
  xit('Check Redmine versions implementation',  function()  {
    func.GoToPage()
    btn.roadmapButton()
    .click()
    obj.roadmapImplementationVersion()
    .click()
  })
  xit('Check Issues page filtration',  function()  {
    func.GoToPage()
    btn.issuesButton()
    .click()
    obj.issuesAddFilter()
    .select("tracker_id")
    obj.issuesAddTrackerFilter()
    .select("2")
    obj.issuesApplyButton()
    .click()
  })
  xit('Add new issue',  function()  {
    func.GoToPage()
    func.LogIn()
    btn.newIssueButton()
    .click()
    func.makeNewIssue()
  })
  xit('Check news page',  function()  {
    func.GoToPage()
    btn.newsButton()
    .click()
    obj.news()
    .click()
  })
  xit('Check forums page',  function()  {
    func.GoToPage()
    btn.forumButton()
    .click()
    obj.forumsHelpTopic()
    .click()
  })
  xit('Check repository page',  function()  {
    func.GoToPage()
    btn.repoButton()
    .click()
    obj.repoPageCheck()
  })
  xit('Change Redmine guide language',  function()  {
    func.GoToPage()
    btn.helpButton()
    .click()
    obj.navigateToTranslation()
    .click()
    obj.translateToFrench()
    .click()
  })
  xit('Check search filtation',  function()  {
    func.GoToPage()
    obj.searchInput()
    obj.searchMessagesFilter()
    .click()
  })
  xit('Buy redmine book',  function()  {
    func.GoToPage()
    cy.scrollTo('bottom')
    obj.bookImage()
  })
  xit('Check defect details through roadmap',  function()  {
    func.GoToPage()
    btn.roadmapButton()
    .click()
    obj.roadmapImplementationVersion()
    .click()
    obj.defect()
    .click()
  })
  xit('Increase number of defects shown',  function()  {
    func.GoToPage()
    btn.issuesButton()
    .click()
    obj.issuesShow50Issues()
    .click()
  })
  xit('Check project administarator profile',  function()  {
    func.GoToPage()
    btn.projectsButton()
    .click()
    btn.redmineProjectButton()
    .click()
    obj.redmimeProjectAdministrator()
    .click()
  })
  xit('Сheck redmine plugin details',  function()  {
    func.GoToPage()
    btn.resourcesPluginsButton()
    .click()
    obj.plugin()
    .click()
  })
  xit('Check Changelog details by version',  function()  {
    func.GoToPage()
    btn.resourcesChangelogButton()
    .click()
    obj.changelog5series()
    .click()
  })
  xit('Сheck security vulnerability details',  function()  {
    func.GoToPage()
    btn.resourcesSecurityButton()
    .click()
    obj.securityVulnerabilityDetail()
  })
  xit('Check list of companies that uses redmine',  function()  {
    func.GoToPage()
    cy.scrollTo('bottom')
    obj.companiesThatUseRedminePage()
    .click()
  })
  xit('Check profile details of user that added news',  function()  {
    func.GoToPage()
    btn.newsButton()
    .click()
    obj.news()
    .click()
    obj.userThatAddNews()
    .click()
  })
  xit('Check forum topic sorting',  function()  {
    func.GoToPage()
    btn.forumButton()
    .click()
    obj.forumsHelpTopic()
    .click()
    obj.forumsSortByDate()
    .click()
  })
  xit('Check forum issue details',  function()  {
    func.GoToPage()
    btn.forumButton()
    .click()
    obj.forumsHelpTopic()
    .click()
    obj.forumsUserIssue()
    .click()
  })
  xit('Check issues page sorting',  function()  {
    func.GoToPage()
    btn.issuesButton()
    .click()
    obj.issuesSortByDate()
    .click()
  })
  xit('Check roadmap filtration',  function()  {
    func.GoToPage()
    btn.roadmapButton()
    .click()
    obj.roadmapDefectCheckbox()
    .uncheck()
    obj.roadmapFeatureCheckbox()
    .uncheck()
    obj.roadmapApply()
    .click()
  })
  xit('Check activity filtration',  function()  {
    func.GoToPage()
    btn.activityButton()
    .click()
    obj.activityIssuesFiltration()
    .click()
  })
  it('Check API guide',  function()  {
    func.GoToPage()
    btn.helpButton()
    .click()
    obj.helpDeveloperGuide()
    .scrollIntoView()
    obj.helpRedmineRestApi()
    .click()
    obj.apiIssuesPageGuide()
    .click()
  })
 
  //Negative testing
  xit('Register without data',  function()  {
    func.GoToPage()
    btn.registerButton()
    .click()
    btn.submitRegisterButton()
    .click()
    obj.errorCheck()
  })
  xit('Register with incorrect email',  function()  {
    func.GoToPage()
    btn.registerButton()
    .click()
    obj.registerEnterEmail()
    btn.submitRegisterButton()
    .click()
    obj.errorCheck()
  })
})

